---
title: "Exploratory analysis: community engagement"
author: "Pamela Russell"
date: "8/16/2017"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = T, warning = F, message = F)
```

```{r}
rm(list=ls())
suppressPackageStartupMessages(library(bigrquery))
suppressPackageStartupMessages(library(dplyr))
suppressPackageStartupMessages(library(ggplot2))
source("~/Dropbox/Documents/Github_mining/src/R/project_info.R")
repo_level_data <- load_repo_features()
```

```{r}
# Number of forks by repo
ggplot(data = repo_level_data, aes(log10(forks_count + 1))) + 
  geom_histogram(bins = 100) + 
  xlab("log10(number of forks + 1)") + 
  ylab("Number of repos") + 
  ggtitle("Histogram of number of forks per repo")
```

Explanation of watchers, subscribers, stars, etc:

https://github.com/blog/1204-notifications-stars

https://developer.github.com/changes/2012-09-05-watcher-api/

https://developer.github.com/v3/activity/starring/

```{r}
# Number of watchers by repo
ggplot(data = repo_level_data, aes(log10(watchers_count + 1))) + 
  geom_histogram(bins = 100) + 
  xlab("log10(number of watchers + 1)") + 
  ylab("Number of repos") + 
  ggtitle("Histogram of number of watchers per repo")
```

```{r}
# Number of subscribers by repo
ggplot(data = repo_level_data, aes(log10(subscribers_count + 1))) + 
  geom_histogram(bins = 100) + 
  xlab("log10(number of subscribers + 1)") + 
  ylab("Number of repos") + 
  ggtitle("Histogram of number of subscribers per repo")
```



