---
title: 'Exploratory analysis: repo-level metrics'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = F, warning = F, message = F)
```

```{r}
rm(list=ls())
suppressPackageStartupMessages(library(bigrquery))
suppressPackageStartupMessages(library(dplyr))
suppressPackageStartupMessages(library(ggplot2))
setwd("~/Documents/Github_mining/src/R/exploratory_analysis")
```


```{r}
# Project info
proj <- "github-bioinformatics-157418"
ds_gh <- "test_repos"
ds_analysis <- "test_repos_analysis_results"
```


```{r}
# Join all repo-level data
# Load all the repo-level data from BigQuery and do a full join by repo name
table_list <- c("language_list_by_repo", "num_languages_by_repo", "lines_of_code_by_repo", 
                "project_duration_by_repo", "num_forks_by_repo", "num_watchers_by_repo", 
                "num_actors_by_repo", "num_devs_by_repo", "commit_types_by_repo", "test_cases_by_repo")
repo_level_data <- data.frame(repo_name = character())
for(table in table_list) {
  table_data <- list_tabledata(project = proj, dataset = ds_analysis, table = table)
  repo_level_data <- full_join(repo_level_data, table_data, by = "repo_name")
}
```


```{r}
# Add languages
lang_bytes <- list_tabledata(project = proj, dataset = ds_analysis, table = "bytes_by_language")
lang_list <- lang_bytes$language_name
lang_list_by_repo <- sapply(repo_level_data$languages, function(x) strsplit(x, ","))
for(lang in lang_list) {
  repo_level_data[[lang]] <- unlist(lapply(lang_list_by_repo, function(x) lang %in% x))
}
repo_level_data <- repo_level_data %>% rename(Cpp = `C++`)
```


```{r}
# Languages of interest
top_languages <- c("Python", "Shell", "Cpp", "R", "C", "Perl", "JavaScript", "Java",
                              "Objective-C", "Matlab", "Ruby", "PHP", "Haskell", "Go", "Lua",
                              "Roff", "Scala", "M", "Tcl")
```

# Histograms of repo-level metrics

```{r}
# Number of languages
qplot(repo_level_data$num_languages,
      geom = "histogram",
      binwidth = 1,
      main = "Histogram of number of languages",
      xlab = "Number of languages",
      ylab = "Number of repos",
      fill = I("darkmagenta")) +
  theme(plot.title = element_text(size = 24),
        axis.title.x = element_text(size = 16),
        axis.title.y = element_text(size = 16))
```


```{r}
# Lines of code
qplot(log10(repo_level_data$lines_of_code),
      geom = "histogram",
      main = "Histogram of lines of code",
      xlab = "Total lines of code (log10)",
      ylab = "Number of repos",
      fill = I("darkmagenta")) +
  theme(plot.title = element_text(size = 24),
        axis.title.x = element_text(size = 16),
        axis.title.y = element_text(size = 16))
```


```{r}
# Project duration
qplot(repo_level_data$commit_span_days,
      geom = "histogram",
      binwidth = 100,
      main = "Histogram of project duration",
      xlab = "Time from first commit to latest commit (years)",
      ylab = "Number of repos",
      fill = I("darkmagenta")) +
  theme(plot.title = element_text(size = 24),
        axis.title.x = element_text(size = 16),
        axis.title.y = element_text(size = 16)) +
  scale_x_continuous(breaks = function(x) {seq(0, x[2], by=365)},
                     labels = function(x) x / 365)
```


```{r}
# Number of forks
qplot(repo_level_data$num_forks,
      geom = "histogram",
      main = "Histogram of number of forks",
      xlab = "Number of forks",
      ylab = "Number of repos",
      fill = I("darkmagenta")) +
  theme(plot.title = element_text(size = 24),
        axis.title.x = element_text(size = 16),
        axis.title.y = element_text(size = 16))
```


```{r}
# Number of watchers
qplot(repo_level_data$num_watchers,
      geom = "histogram",
      main = "Histogram of number of watchers",
      xlab = "Number of watchers",
      ylab = "Number of repos",
      fill = I("darkmagenta")) +
  theme(plot.title = element_text(size = 24),
        axis.title.x = element_text(size = 16),
        axis.title.y = element_text(size = 16))
```


```{r}
# Number of commit authors
qplot(repo_level_data$num_commit_authors,
      geom = "histogram",
      main = "Histogram of number of commit authors",
      xlab = "Number of commit authors",
      ylab = "Number of repos",
      fill = I("darkmagenta")) +
  theme(plot.title = element_text(size = 24),
        axis.title.x = element_text(size = 16),
        axis.title.y = element_text(size = 16))
```


```{r}
# Number of commits
qplot(log10(repo_level_data$num_commits),
      geom = "histogram",
      main = "Histogram of number of commits",
      xlab = "Number of commits (log10)",
      ylab = "Number of repos",
      fill = I("darkmagenta")) +
  theme(plot.title = element_text(size = 24),
        axis.title.x = element_text(size = 16),
        axis.title.y = element_text(size = 16))
```


```{r}
# Number of test cases
qplot(log10(repo_level_data$num_test_cases),
      geom = "histogram",
      main = "Histogram of number of test cases",
      xlab = "Number of test cases (log10)",
      ylab = "Number of repos",
      fill = I("darkmagenta")) +
  theme(plot.title = element_text(size = 24),
        axis.title.x = element_text(size = 16),
        axis.title.y = element_text(size = 16))
```


```{r}
# Total lines of test cases
qplot(log10(repo_level_data$total_lines_test_cases),
      geom = "histogram",
      main = "Histogram of total lines of test cases",
      xlab = "Total lines of test cases (log10)",
      ylab = "Number of repos",
      fill = I("darkmagenta")) +
  theme(plot.title = element_text(size = 24),
        axis.title.x = element_text(size = 16),
        axis.title.y = element_text(size = 16))
```

# Project duration

```{r}
# Scatter plot of latest commit vs first commit
min_date <- min(repo_level_data$first_commit, na.rm = T)
max_date <- max(repo_level_data$last_commit, na.rm = T)
ggplot(data = repo_level_data, aes(x = first_commit, y = last_commit)) +
  geom_point(aes(color = commit_span_days)) +
  scale_color_gradientn(colors = c("red", "green", "blue"), 
                        name = "Commit span (years)",
                        labels = function(x) round(x / 365)) +
  coord_cartesian(xlim = c(min_date, max_date),
                  ylim = c(min_date, max_date)) +
  labs(title = "Project time spans",
       x = "First commit",
       y = "Latest commit") +
  theme(plot.title = element_text(size = 24),
        axis.title.x = element_text(size = 16),
        axis.title.y = element_text(size = 16))
```





