---
title: 'Exploratory analysis: programming languages'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = T)
```

```{r echo = F}
rm(list=ls())
suppressPackageStartupMessages(library(bigrquery))
suppressPackageStartupMessages(library(dplyr))
suppressPackageStartupMessages(library(ggplot2))
setwd("~/Documents/Github_mining/src/R/exploratory_analysis")
```

### Project info

```{r cache = T}
proj <- "github-bioinformatics-157418"
ds_gh <- "test_repos"
ds_analysis <- "test_repos_analysis_results"
```

### Load the data from BigQuery

```{r cache = T, fig.height = 7, fig.width = 8}
repos_by_lang <- list_tabledata(project = proj, dataset = ds_analysis, table = "num_repos_by_language")
repos_by_lang <- arrange(repos_by_lang, desc(num_repos))
lang_by_repo <- list_tabledata(project = proj, dataset = ds_analysis, table = "language_list_by_repo")
lang_bytes <- list_tabledata(project = proj, dataset = ds_analysis, table = "bytes_by_language")
```

### Number of repos by language

```{r}
# Get the top languages
top_langs <- arrange(repos_by_lang[1:30,], num_repos)
top_langs$language_name <- factor(top_langs$language_name, levels = top_langs$language_name)

# Plot number of repos by language
ggplot(top_langs, aes(x = factor(language_name), y = num_repos)) + 
  geom_bar(stat = "identity") +
  coord_flip() +
  labs(y = paste("Number of repos including language (n = ", nrow(lang_by_repo), ")", sep = ""),
       x = "Language",
       title = "Number of repos by language") +
  theme(plot.title = element_text(size = 24),
        axis.title.x = element_text(size = 16),
        axis.title.y = element_text(size = 16))
```

### Number of repos by language pair

```{r}
# Identify languages
lang <- sort(lang_bytes$language_name)
nlang <- length(lang)
npair <- nlang * (nlang - 1) / 2

mkPair <- function(l1, l2) {
  paste(l1, l2, sep=", ")
}

# Make list of all possible language pairs
all_pairs <- apply(expand.grid(lang, lang), 1, function(x) {
      l1 <- as.character(x[1])
      l2 <- as.character(x[2])
      if(l1 < l2) {
        mkPair(l1, l2)
      }
      else NA
})
all_pairs <- all_pairs[which(!is.na(all_pairs))]

# Empty data frame of pair counts
pair_count <- data.frame(num_repos = matrix(0, nrow = npair, ncol = 1), 
                         row.names = all_pairs)

# Function to update pair counts based on language list for one repo
update_pair_count <- function(cslist) {
  l <- unlist(strsplit(cslist, ',', fixed = T))
  l <- l[which(!is.na(l))]
  apply(expand.grid(l, l), 1, function(x) {
    l1 <- as.character(x[1])
    l2 <- as.character(x[2])
    if(l1 < l2) {
      pair_count[mkPair(l1, l2), 1] <<- pair_count[mkPair(l1, l2), 1] + 1
    }
  })
}

# Update the pair counts for all repos
x <- lapply(lang_by_repo$languages, update_pair_count)
rm(x)

# Sort pairs by number of repos
pair_count$languages <- row.names(pair_count)
pair_count <- arrange(pair_count, desc(num_repos))

# Get the top pairs
top_pairs <- pair_count[1:30,]
top_pairs <- arrange(top_pairs, num_repos)
top_pairs$languages <- factor(top_pairs$languages, levels = top_pairs$languages)

# Plot number of repos by language pair
ggplot(top_pairs, aes(x = languages, y = num_repos)) + 
  geom_bar(stat = "identity") +
  coord_flip() +
  labs(y = paste("Number of repos including both languages (n = ", nrow(lang_by_repo), ")", sep = ""),
       x = "Languages",
       title = "Number of repos by language pair") +
  theme(plot.title = element_text(size = 24),
        axis.title.x = element_text(size = 16),
        axis.title.y = element_text(size = 16))
```

### Total size of source files by language

Use BigQuery's built-in "languages" table, not our CLOC results

```{r}
# Construct a vector of number of bytes per language
language <- lang_bytes$language_name
bytes <- lang_bytes$total_bytes
names(bytes) <- language
bytes <- bytes[order(-bytes)]

# Get the top languages
num_top_languages <- 25
top_languages <- bytes[1:num_top_languages]
names(top_languages) <- names(bytes)[1:num_top_languages]
top_languages <- top_languages[order(top_languages)]
# All other languages
others <- sum(bytes[1+num_top_languages:length(bytes)], na.rm=T)
new_names <- c("All others", names(top_languages))
top_languages <- c(others, top_languages)
names(top_languages) <- new_names

# Plot bytes per language
par(mar=c(5,12,4,2))
barplot(
  t(as.matrix(top_languages)),
  horiz = T,
  col = "darkorchid4",
  las=1,
  main="Total size of source files",
  axes=F
)
axis(1, at=c(0, 100000000, 200000000, 300000000), labels=c("0", "100Mb", "200Mb", "300Mb"))
```

