#!/bin/bash

###################################################
# Parse a text file containing a list of abstracts 
# and other metadata exported from a PubMed query;
# get some Github repo names  
# 
# This is just to get some repo names for testing
# purposes. This is not all the repos in the PubMed
# file, and may include some incorrect names.
###################################################


if [ "$#" -ne 1 ]; then
	echo -e "\nUsage: parsePubmedResponse <text file of authorInfos exported from PubMed query>\n"
	exit
fi


cat $1 \
| grep github.com \
| awk '{for(i=1; i<=NF; i++) {print $i}}' \
| grep -E 'github\.com/*/' \
| awk -F"github.com" '{print $2}' \
| perl -pi -e 's/\.$//g' \
| perl -pi -e 's/\)$//g' \
| awk -F/ ' NF > 2 && $3 != "" {print $2 "/" $3}' \
| awk -F"Contact:" '{print $1}' \
| perl -pi -e 's/[,;\)\]\}]//g' \
| perl -pi -e 's/\.$//g' \
| perl -pi -e 's/\+$//g' \
| awk -F/ 'NF == 2 && $1 != ""' \
| sort -u



