#!/bin/bash

###################################################
# Parse a text file containing a list of abstracts 
# and other metadata exported from a PubMed query
###################################################

if [ "$#" -ne 1 ]; then
	echo -e "\nUsage: parsePubmedResponse <text file of authorInfos exported from PubMed query>\n"
	exit
fi


cat $1 | awk '
	$1 ~ /^[0-9]+\.$/ && $2 ~ /^[a-zA-Z]/ {
		info = $0; while(NF > 0) {getline; info = info " " $0}; getline;
		title = $0; while(NF > 0) {getline; title = title " " $0}; getline;
		authors = $0; while(NF > 0) {getline; authors = authors " " $0}; getline;
		authorInfo = $0; while(NF > 0) {getline; authorInfo = authorInfo " " $0}; getline;
		abstract = $0; while(NF > 0) {getline; abstract = abstract " " $0}; getline;		
		print info "\t" title "\t" authors "\t" authorInfo "\t" abstract "\t";
	}
' \
| perl -pi -e 's/Version \d+\. F1000Res\./F1000Res\./g' \
| perl -pi -e 's/^[0-9]+\. //g' 


